// export const mySkills = [
//   { title: "Tailwind CSS", icon: "tailwind" },
//   { title: "shadcn/ui", icon: "shadcn" },
//   { title: "Material UI", icon: "material" },
//   { title: "Framer Motion", icon: "framer" },
//   { title: "JavaScript", icon: "javascript" },
//   { title: "TypeScript", icon: "typescript" },
//   { title: "ReactJS", icon: "react" },
//   { title: "React Query", icon: "reactquery" },
//   { title: "Redux", icon: "redux" },
//   { title: "NextJS", icon: "nextjs" },
//   { title: "NodeJS", icon: "nodejs" },
//   { title: "ExpressJS", icon: "express" },
//   { title: "MongoDB", icon: "mongodb" },
//   { title: "PostgreSQL", icon: "postgresql" },
//   { title: "Supabase", icon: "supabase" },
//   { title: "Prisma", icon: "prisma" },
//   { title: "GraphQL", icon: "graphql" },
//   { title: "Docker", icon: "docker" },
//   { title: "Vercel", icon: "vercel" },
//   { title: "Git", icon: "git" },
//   { title: "GitHub", icon: "github" },
//   { title: "ESLint", icon: "eslint" },
//   { title: "Postman", icon: "postman" },
//   { title: "npm", icon: "npm" },
// ];
export const mySkills = [
  { title: "JavaScript", icon: "javascript" },
  { title: "TypeScript", icon: "typescript" },
  { title: "ReactJS", icon: "react" },
  { title: "React Native", icon: "reactnative" },
  { title: "NodeJS", icon: "nodejs" },
  { title: "ExpressJS", icon: "express" },
  { title: "MongoDB", icon: "mongodb" },
  { title: "MySQL / SQL", icon: "mysql" },
  { title: "Spring Boot", icon: "springboot" },
  { title: "Supabase", icon: "supabase" },
  { title: "Razorpay", icon: "razorpay" },
  { title: "HTML5", icon: "html5" },
  { title: "CSS3", icon: "css3" },
  { title: "Git", icon: "git" },
  { title: "GitHub", icon: "github" },
  { title: "Postman", icon: "postman" },
  { title: "VS Code", icon: "vscode" },
  { title: "Responsive Design", icon: "responsive" },
  { title: "RESTful APIs", icon: "restapi" },
  { title: "Firebase", icon: "firebase" },
];
